{% set name = "arviz" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57d80eacc51909f18e6ab63c96a6b02227c3b077c5ffa406d5f4dabe03b8f019
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools >=38.4
    - matplotlib-base >=3.0
    - numpy >=1.12
    - scipy >=0.19
    - packaging
    - pandas >=0.23
    - xarray >=0.16.1
    - netcdf4
    - typing_extensions >=3.7.4.3,<4
    - xarray-einstats >=0.2

test:
  imports:
    - arviz
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/arviz-devs/arviz
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Exploratory analysis of Bayesian models with Python

  description: |
    ArviZ (pronounced "AR-vees") is a Python package for exploratory analysis
    of Bayesian models. Includes functions for posterior analysis, model
    checking, comparison and diagnostics.

  doc_url: https://arviz-devs.github.io/arviz/index.html
  dev_url: https://github.com/arviz-devs/arviz

extra:
  recipe-maintainers:
    - dhirschfeld
    - ericmjl
    - canyon289
    - aloctavodia
    - ColCarroll
    - ahartikainen
    - OriolAbril
