{% set name = "arviz" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ffd6a632af6b28eb5dac7e3b938223ffa202308dc67c58b55a404565a985bd2
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3.10
    - setuptools >=60.0
    - matplotlib-base >=3.5
    - numpy >=1.23,<2.0
    - scipy >=1.9
    - packaging
    - pandas >=1.5
    - xarray >=2022.6.0
    - h5netcdf >=1.0.2
    - typing_extensions >=4.1.0
    - xarray-einstats >=0.3
    - dm-tree >=0.1.8

test:
  imports:
    - arviz
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/arviz-devs/arviz
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Exploratory analysis of Bayesian models with Python

  description: |
    ArviZ (pronounced "AR-vees") is a Python package for exploratory analysis
    of Bayesian models. Includes functions for posterior analysis, model
    checking, comparison and diagnostics.

  doc_url: https://python.arviz.org
  dev_url: https://github.com/arviz-devs/arviz

extra:
  recipe-maintainers:
    - maresb
    - ericmjl
    - canyon289
    - aloctavodia
    - ColCarroll
    - ahartikainen
    - OriolAbril
