schema_version: 1

context:
  name: arviz
  version: "1.0.0"
  python_min: "3.12"

recipe:
  name: arviz-suite
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 9bc978e8b590d5ee88fe024c4fa10e214dc42c31329e645b2ad998419cbe7ff6

build:
  number: 1

outputs:
  - package:
      name: arviz
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python ${{ python_min }}.*
        - flit-core >=3.4,<4
        - pip
      run:
        - python >=${{ python_min }}
        - arviz-base >=1.0.0,<1.1.0
        - arviz-stats >=1.0.0,<1.1.0
        - arviz-plots >=1.0.0,<1.1.0
        - matplotlib-base >=3.9
    tests:
      - python:
          imports:
            - arviz
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - 3.*
  - package:
      name: arviz-bokeh
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python ${{ python_min }}.*
        - flit-core >=3.4,<4
        - pip
      run:
        - python >=${{ python_min }}
        - arviz-base >=1.0.0,<1.1.0
        - arviz-stats >=1.0.0,<1.1.0
        - arviz-plots >=1.0.0,<1.1.0
        - bokeh >=3.4
    tests:
      - python:
          imports:
            - arviz
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - 3.*
  - package:
      name: arviz-plotly
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python ${{ python_min }}.*
        - flit-core >=3.4,<4
        - pip
      run:
        - python >=${{ python_min }}
        - arviz-base >=1.0.0,<1.1.0
        - arviz-stats >=1.0.0,<1.1.0
        - arviz-plots >=1.0.0,<1.1.0
        - plotly >=5.19
        - webcolors
    tests:
      - python:
          imports:
            - arviz
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - 3.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Exploratory analysis of Bayesian models with Python
  description: |
    ArviZ (pronounced "AR-vees") is a Python package for exploratory analysis
    of Bayesian models. Includes functions for posterior analysis, model
    checking, comparison and diagnostics.

  homepage: https://python.arviz.org
  repository: https://github.com/arviz-devs/arviz
  documentation: https://python.arviz.org

extra:
  recipe-maintainers:
    - maresb
    - ericmjl
    - canyon289
    - aloctavodia
    - ColCarroll
    - ahartikainen
    - OriolAbril
