schema_version: 1

context:
  name: arviz
  version: 1.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 9bc978e8b590d5ee88fe024c4fa10e214dc42c31329e645b2ad998419cbe7ff6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=60.0.0
  run:
    - python >=${{ python_min }}
    - arviz-plots >=1.0.0,<1.1.0
    - arviz-base >=1.0.0,<1.1.0
    - arviz-stats >=1.0.0,<1.1.0
tests:
  - python:
      imports:
        - arviz
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Exploratory analysis of Bayesian models with Python
  description: |
    ArviZ (pronounced "AR-vees") is a Python package for exploratory analysis
    of Bayesian models. Includes functions for posterior analysis, model
    checking, comparison and diagnostics.

  homepage: https://github.com/arviz-devs/arviz
  repository: https://github.com/arviz-devs/arviz
  documentation: https://python.arviz.org

extra:
  recipe-maintainers:
    - maresb
    - ericmjl
    - canyon289
    - aloctavodia
    - ColCarroll
    - ahartikainen
    - OriolAbril
